name: Deploy f2lb backend on code push
on: [push]
jobs:
  DeploySite:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: checkout code
        uses: actions/checkout@v3
      - name: run deploy as systemd
        run: bash deploy.sh
